package sn.edu.ugb.student.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueAcademiqueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAcademiqueAllPropertiesEquals(HistoriqueAcademique expected, HistoriqueAcademique actual) {
        assertHistoriqueAcademiqueAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueAcademiqueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAcademiqueAllUpdatablePropertiesEquals(HistoriqueAcademique expected, HistoriqueAcademique actual) {
        assertHistoriqueAcademiqueUpdatableFieldsEquals(expected, actual);
        assertHistoriqueAcademiqueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAcademiqueAutoGeneratedPropertiesEquals(HistoriqueAcademique expected, HistoriqueAcademique actual) {
        assertThat(actual)
            .as("Verify HistoriqueAcademique auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAcademiqueUpdatableFieldsEquals(HistoriqueAcademique expected, HistoriqueAcademique actual) {
        assertThat(actual)
            .as("Verify HistoriqueAcademique relevant properties")
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateInscription()).as("check dateInscription").isEqualTo(expected.getDateInscription()))
            .satisfies(a -> assertThat(a.getEtudiantId()).as("check etudiantId").isEqualTo(expected.getEtudiantId()))
            .satisfies(a -> assertThat(a.getSemestreId()).as("check semestreId").isEqualTo(expected.getSemestreId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAcademiqueUpdatableRelationshipsEquals(HistoriqueAcademique expected, HistoriqueAcademique actual) {
        // empty method
    }
}
