package sn.edu.ugb.student.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionAllPropertiesEquals(Inscription expected, Inscription actual) {
        assertInscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertInscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionAllUpdatablePropertiesEquals(Inscription expected, Inscription actual) {
        assertInscriptionUpdatableFieldsEquals(expected, actual);
        assertInscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionAutoGeneratedPropertiesEquals(Inscription expected, Inscription actual) {
        assertThat(actual)
            .as("Verify Inscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionUpdatableFieldsEquals(Inscription expected, Inscription actual) {
        assertThat(actual)
            .as("Verify Inscription relevant properties")
            .satisfies(a -> assertThat(a.getEnCours()).as("check enCours").isEqualTo(expected.getEnCours()))
            .satisfies(a -> assertThat(a.getEtudiantId()).as("check etudiantId").isEqualTo(expected.getEtudiantId()))
            .satisfies(a -> assertThat(a.getFiliereId()).as("check filiereId").isEqualTo(expected.getFiliereId()))
            .satisfies(a -> assertThat(a.getSemestreId()).as("check semestreId").isEqualTo(expected.getSemestreId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscriptionUpdatableRelationshipsEquals(Inscription expected, Inscription actual) {
        // empty method
    }
}
