# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTViODMwZjZlNWJhYTJkM2U2Y2ZmODY5NzBhYWZlMmYyZGE0NThmMWNmYjI1ZWIwNmZhZWZiY2MyODcxOWI3YTg2ZTI2MDRlYTQxMDVjODNhNTUzZmM1YjU0MWJjMmFkY2Y3YTRhZTM0MWFjZjBhNDE0ZWY0ZmNjODMzNDFlN2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
