package sn.edu.ugb.teacher.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AffectationEnseignementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationEnseignementAllPropertiesEquals(AffectationEnseignement expected, AffectationEnseignement actual) {
        assertAffectationEnseignementAutoGeneratedPropertiesEquals(expected, actual);
        assertAffectationEnseignementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationEnseignementAllUpdatablePropertiesEquals(
        AffectationEnseignement expected,
        AffectationEnseignement actual
    ) {
        assertAffectationEnseignementUpdatableFieldsEquals(expected, actual);
        assertAffectationEnseignementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationEnseignementAutoGeneratedPropertiesEquals(
        AffectationEnseignement expected,
        AffectationEnseignement actual
    ) {
        assertThat(actual)
            .as("Verify AffectationEnseignement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationEnseignementUpdatableFieldsEquals(
        AffectationEnseignement expected,
        AffectationEnseignement actual
    ) {
        assertThat(actual)
            .as("Verify AffectationEnseignement relevant properties")
            .satisfies(a -> assertThat(a.getAnneeAcademique()).as("check anneeAcademique").isEqualTo(expected.getAnneeAcademique()))
            .satisfies(a -> assertThat(a.getEnseignantId()).as("check enseignantId").isEqualTo(expected.getEnseignantId()))
            .satisfies(a -> assertThat(a.getCoursId()).as("check coursId").isEqualTo(expected.getCoursId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationEnseignementUpdatableRelationshipsEquals(
        AffectationEnseignement expected,
        AffectationEnseignement actual
    ) {
        // empty method
    }
}
