package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurriculumAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumAllPropertiesEquals(Curriculum expected, Curriculum actual) {
        assertCurriculumAutoGeneratedPropertiesEquals(expected, actual);
        assertCurriculumAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumAllUpdatablePropertiesEquals(Curriculum expected, Curriculum actual) {
        assertCurriculumUpdatableFieldsEquals(expected, actual);
        assertCurriculumUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumAutoGeneratedPropertiesEquals(Curriculum expected, Curriculum actual) {
        assertThat(actual)
            .as("Verify Curriculum auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumUpdatableFieldsEquals(Curriculum expected, Curriculum actual) {
        // Curriculum n'a pas de champs updatables autres que les relations
        // Cette méthode peut rester vide ou contenir des assertions sur d'éventuels champs
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumUpdatableRelationshipsEquals(Curriculum expected, Curriculum actual) {
        assertThat(actual)
            .as("Verify Curriculum relationships")
            .satisfies(a -> assertThat(a.getFiliere()).as("check filiere").isEqualTo(expected.getFiliere()))
            .satisfies(a -> assertThat(a.getUniteEnseignement()).as("check uniteEnseignement").isEqualTo(expected.getUniteEnseignement()))
            .satisfies(a -> assertThat(a.getSemestre()).as("check semestre").isEqualTo(expected.getSemestre()));
    }
}
