package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurriculumAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumAllPropertiesEquals(Curriculum expected, Curriculum actual) {
        assertCurriculumAutoGeneratedPropertiesEquals(expected, actual);
        assertCurriculumAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumAllUpdatablePropertiesEquals(Curriculum expected, Curriculum actual) {
        assertCurriculumUpdatableFieldsEquals(expected, actual);
        assertCurriculumUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumAutoGeneratedPropertiesEquals(Curriculum expected, Curriculum actual) {
        assertThat(actual)
            .as("Verify Curriculum auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumUpdatableFieldsEquals(Curriculum expected, Curriculum actual) {
        assertThat(actual)
            .as("Verify Curriculum relevant properties")
            .satisfies(a -> assertThat(a.getFiliereId()).as("check filiereId").isEqualTo(expected.getFiliereId()))
            .satisfies(a -> assertThat(a.getModuleId()).as("check moduleId").isEqualTo(expected.getModuleId()))
            .satisfies(a -> assertThat(a.getSemestreId()).as("check semestreId").isEqualTo(expected.getSemestreId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumUpdatableRelationshipsEquals(Curriculum expected, Curriculum actual) {
        // empty method
    }
}
