package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SemestreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemestreAllPropertiesEquals(Semestre expected, Semestre actual) {
        assertSemestreAutoGeneratedPropertiesEquals(expected, actual);
        assertSemestreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemestreAllUpdatablePropertiesEquals(Semestre expected, Semestre actual) {
        assertSemestreUpdatableFieldsEquals(expected, actual);
        assertSemestreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemestreAutoGeneratedPropertiesEquals(Semestre expected, Semestre actual) {
        assertThat(actual)
            .as("Verify Semestre auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemestreUpdatableFieldsEquals(Semestre expected, Semestre actual) {
        assertThat(actual)
            .as("Verify Semestre relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemestreUpdatableRelationshipsEquals(Semestre expected, Semestre actual) {
        // empty method
    }
}
