package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UniteEnseignementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteEnseignementAllPropertiesEquals(UniteEnseignement expected, UniteEnseignement actual) {
        assertUniteEnseignementAutoGeneratedPropertiesEquals(expected, actual);
        assertUniteEnseignementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteEnseignementAllUpdatablePropertiesEquals(UniteEnseignement expected, UniteEnseignement actual) {
        assertUniteEnseignementUpdatableFieldsEquals(expected, actual);
        assertUniteEnseignementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteEnseignementAutoGeneratedPropertiesEquals(UniteEnseignement expected, UniteEnseignement actual) {
        assertThat(actual)
            .as("Verify UniteEnseignement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteEnseignementUpdatableFieldsEquals(UniteEnseignement expected, UniteEnseignement actual) {
        assertThat(actual)
            .as("Verify UniteEnseignement relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getFiliereId()).as("check filiereId").isEqualTo(expected.getFiliereId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteEnseignementUpdatableRelationshipsEquals(UniteEnseignement expected, UniteEnseignement actual) {
        // empty method
    }
}
